2018-08-15 21:26:51 [WARNING] 获取资产信息失败: int() argument must be a string or a number, not 'NoneType'
2018-08-15 21:26:53 [WARNING] 获取资产信息失败: int() argument must be a string or a number, not 'NoneType'
2018-08-15 21:28:20 [ERROR] run model failed: this task 'ios_command' has extra params, which is only allowed in the following modules: command, win_command, shell, win_shell, script, include, include_vars, add_host, group_by, set_fact, raw, meta
2018-08-15 21:30:10 [ERROR] run model failed: this task 'ios_command' has extra params, which is only allowed in the following modules: command, win_command, shell, win_shell, script, include, include_vars, add_host, group_by, set_fact, raw, meta
2018-08-15 21:34:09 [ERROR] run playbook failed: The field 'hosts' has an invalid value, which includes an undefined variable. The error was: 'hosts' is undefined

The error appears to have been in '/mnt/OpsManage/upload/playbook/online-ee5d679f.yaml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- hosts: "{{hosts}}"
  ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"

2018-08-15 21:35:15 [ERROR] run playbook failed: The field 'hosts' has an invalid value, which includes an undefined variable. The error was: 'hosts' is undefined

The error appears to have been in '/mnt/OpsManage/upload/playbook/online-ee5d679f.yaml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- hosts: "{{hosts}}"
  ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"

2018-08-26 16:18:48 [WARNING] 获取SQL审核配置信息失败: SQL_Audit_Control matching query does not exist.
2018-08-26 16:18:48 [WARNING] 获取Inception服务器信息失败: Inception_Server_Config matching query does not exist.
2018-08-26 16:22:33 [WARNING] 获取SQL审核配置信息失败: SQL_Audit_Control matching query does not exist.
2018-08-26 16:22:33 [WARNING] 获取Inception服务器信息失败: Inception_Server_Config matching query does not exist.
2018-09-10 22:23:20 [WARNING] 获取SQL审核配置信息失败: SQL_Audit_Control matching query does not exist.
2018-09-10 22:23:20 [WARNING] 获取Inception服务器信息失败: Inception_Server_Config matching query does not exist.
2018-09-11 21:26:34 [WARNING] 获取SQL审核配置信息失败: SQL_Audit_Control matching query does not exist.
2018-09-11 21:26:34 [WARNING] 获取Inception服务器信息失败: Inception_Server_Config matching query does not exist.
2018-09-11 21:26:56 [WARNING] 获取SQL审核配置信息失败: SQL_Audit_Control matching query does not exist.
2018-09-11 21:26:56 [WARNING] 获取Inception服务器信息失败: Inception_Server_Config matching query does not exist.
2019-01-05 16:47:54 [INFO] HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2019-01-05 16:47:54 [INFO] Configuring endpoint tcp:port=8000:interface=0.0.0.0
2019-01-05 16:47:54 [INFO] Listening on TCP address 0.0.0.0:8000
2019-01-05 17:35:32 [INFO] HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2019-01-05 17:35:32 [INFO] Configuring endpoint tcp:port=8000:interface=0.0.0.0
2019-01-05 17:35:32 [INFO] Listening on TCP address 0.0.0.0:8000
2019-01-05 17:37:53 [INFO] HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2019-01-05 17:37:53 [INFO] Configuring endpoint tcp:port=8000:interface=0.0.0.0
2019-01-05 17:37:53 [INFO] Listening on TCP address 0.0.0.0:8000
2019-01-05 17:38:52 [INFO] HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2019-01-05 17:38:52 [INFO] Configuring endpoint tcp:port=8000:interface=0.0.0.0
2019-01-05 17:38:52 [INFO] Listening on TCP address 0.0.0.0:8000
2019-01-05 17:39:02 [WARNING] uid=tony,ou=people,dc=opsmanage,dc=com does not have a value for the attribute givenName
2019-01-05 17:42:32 [INFO] HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2019-01-05 17:42:32 [INFO] Configuring endpoint tcp:port=8000:interface=0.0.0.0
2019-01-05 17:42:32 [INFO] Listening on TCP address 0.0.0.0:8000
2019-01-05 17:42:41 [ERROR] search_s(''ou=People,dc=opsmanage,dc=com'', 2, '(cn=alex)') raised INVALID_DN_SYNTAX({'desc': 'Invalid DN syntax', 'info': 'invalid DN'},)
2019-01-05 17:43:19 [INFO] HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2019-01-05 17:43:19 [INFO] Configuring endpoint tcp:port=8000:interface=0.0.0.0
2019-01-05 17:43:19 [INFO] Listening on TCP address 0.0.0.0:8000
2019-01-05 17:43:25 [WARNING] uid=alex,ou=people,dc=opsmanage,dc=com does not have a value for the attribute givenName
2019-01-05 17:45:08 [INFO] HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2019-01-05 17:45:08 [INFO] Configuring endpoint tcp:port=8000:interface=0.0.0.0
2019-01-05 17:45:08 [INFO] Listening on TCP address 0.0.0.0:8000
2019-01-05 17:46:02 [INFO] HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2019-01-05 17:46:02 [INFO] Configuring endpoint tcp:port=8000:interface=0.0.0.0
2019-01-05 17:46:02 [INFO] Listening on TCP address 0.0.0.0:8000
2019-01-05 17:47:28 [WARNING] uid=alex,ou=people,dc=opsmanage,dc=com does not have a value for the attribute givenName
2019-01-05 17:47:39 [INFO] HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2019-01-05 17:47:39 [INFO] Configuring endpoint tcp:port=8000:interface=0.0.0.0
2019-01-05 17:47:39 [INFO] Listening on TCP address 0.0.0.0:8000
2019-01-05 17:48:18 [INFO] HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2019-01-05 17:48:18 [INFO] Configuring endpoint tcp:port=8000:interface=0.0.0.0
2019-01-05 17:48:18 [INFO] Listening on TCP address 0.0.0.0:8000
2019-01-05 17:52:49 [INFO] HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2019-01-05 17:52:49 [INFO] Configuring endpoint tcp:port=8000:interface=0.0.0.0
2019-01-05 17:52:49 [INFO] Listening on TCP address 0.0.0.0:8000
2019-01-05 17:54:11 [INFO] HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2019-01-05 17:54:11 [INFO] Configuring endpoint tcp:port=8000:interface=0.0.0.0
2019-01-05 17:54:11 [INFO] Listening on TCP address 0.0.0.0:8000
2019-01-05 17:54:59 [INFO] Connected (version 2.0, client OpenSSH_5.3)
2019-01-05 17:55:00 [INFO] Authentication (publickey) successful!
2019-01-06 09:43:52 [ERROR] assets.py[line:350] 统计项目主机资产失败:(2006, 'MySQL server has gone away')
2019-01-06 09:43:52 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-06 09:43:52 [ERROR] assets.py[line:374] 统计资产类型失败:(2006, 'MySQL server has gone away')
2019-01-06 09:43:52 [ERROR] assets.py[line:358] 统计机房主机资产失败:(2006, 'MySQL server has gone away')
2019-01-06 09:43:52 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-06 14:22:17 [WARNING] users.py[line:28] 获取用户信息失败: User matching query does not exist.
2019-01-06 15:17:38 [WARNING] users.py[line:28] 获取用户信息失败: User matching query does not exist.
2019-01-06 15:18:23 [WARNING] users.py[line:28] 获取用户信息失败: User matching query does not exist.
2019-01-06 15:19:07 [WARNING] users.py[line:28] 获取用户信息失败: User matching query does not exist.
2019-01-06 15:20:50 [WARNING] users.py[line:28] 获取用户信息失败: User matching query does not exist.
2019-01-06 15:21:12 [WARNING] users.py[line:28] 获取用户信息失败: User matching query does not exist.
2019-01-06 15:22:22 [WARNING] users.py[line:28] 获取用户信息失败: User matching query does not exist.
2019-01-06 15:24:52 [WARNING] users.py[line:28] 获取用户信息失败: User matching query does not exist.
2019-01-06 15:34:08 [ERROR] users.py[line:17] UsersManageget_user_group方法
2019-01-06 16:23:47 [ERROR] users.py[line:17] UsersManagemodf_user_group方法
2019-01-06 16:24:51 [ERROR] users.py[line:17] UsersManage没有modf_user_group方法
2019-01-06 16:25:24 [ERROR] users.py[line:17] UsersManage没有modf_user_group方法
2019-01-06 17:02:39 [ERROR] users.py[line:17] UsersManage没有modf_user_perm方法
2019-01-06 17:03:16 [ERROR] users.py[line:17] UsersManage没有modf_user_perm方法
2019-01-06 20:00:23 [ERROR] users.py[line:17] UsersManage没有get_group_group方法
2019-01-06 20:31:12 [ERROR] users.py[line:42] UsersManage没有get_group_perms方法
2019-01-06 21:15:06 [WARNING] app.py[line:210] 获取项目角色管理成员失败: User matching query does not exist.
2019-01-06 21:15:28 [WARNING] app.py[line:210] 获取项目角色管理成员失败: User matching query does not exist.
2019-01-06 21:15:31 [WARNING] app.py[line:210] 获取项目角色管理成员失败: User matching query does not exist.
2019-01-06 21:15:42 [WARNING] app.py[line:210] 获取项目角色管理成员失败: User matching query does not exist.
2019-01-10 20:45:23 [ERROR] assets.py[line:350] 统计项目主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:45:23 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:45:23 [ERROR] assets.py[line:374] 统计资产类型失败:(2006, 'MySQL server has gone away')
2019-01-10 20:45:23 [ERROR] assets.py[line:358] 统计机房主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:45:23 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:45:59 [ERROR] assets.py[line:350] 统计项目主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:45:59 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:45:59 [ERROR] assets.py[line:374] 统计资产类型失败:(2006, 'MySQL server has gone away')
2019-01-10 20:45:59 [ERROR] assets.py[line:358] 统计机房主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:45:59 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:46:14 [ERROR] assets.py[line:350] 统计项目主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:46:14 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:46:14 [ERROR] assets.py[line:374] 统计资产类型失败:(2006, 'MySQL server has gone away')
2019-01-10 20:46:14 [ERROR] assets.py[line:358] 统计机房主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:46:14 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:46:20 [ERROR] assets.py[line:350] 统计项目主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:46:20 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:46:20 [ERROR] assets.py[line:374] 统计资产类型失败:(2006, 'MySQL server has gone away')
2019-01-10 20:46:20 [ERROR] assets.py[line:358] 统计机房主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:46:20 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:49:14 [ERROR] assets.py[line:350] 统计项目主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:49:14 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:49:14 [ERROR] assets.py[line:374] 统计资产类型失败:(2006, 'MySQL server has gone away')
2019-01-10 20:49:14 [ERROR] assets.py[line:358] 统计机房主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:49:14 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:49:26 [ERROR] assets.py[line:350] 统计项目主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:49:26 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:49:26 [ERROR] assets.py[line:374] 统计资产类型失败:(2006, 'MySQL server has gone away')
2019-01-10 20:49:26 [ERROR] assets.py[line:358] 统计机房主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:49:26 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:49:37 [ERROR] assets.py[line:350] 统计项目主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:49:37 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:49:37 [ERROR] assets.py[line:374] 统计资产类型失败:(2006, 'MySQL server has gone away')
2019-01-10 20:49:37 [ERROR] assets.py[line:358] 统计机房主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:49:37 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:49:56 [ERROR] assets.py[line:350] 统计项目主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:49:56 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:49:56 [ERROR] assets.py[line:374] 统计资产类型失败:(2006, 'MySQL server has gone away')
2019-01-10 20:49:56 [ERROR] assets.py[line:358] 统计机房主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:49:56 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:50:31 [ERROR] assets.py[line:350] 统计项目主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:50:31 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:50:31 [ERROR] assets.py[line:374] 统计资产类型失败:(2006, 'MySQL server has gone away')
2019-01-10 20:50:31 [ERROR] assets.py[line:358] 统计机房主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:50:31 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:51:28 [ERROR] assets.py[line:350] 统计项目主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:51:28 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:51:28 [ERROR] assets.py[line:374] 统计资产类型失败:(2006, 'MySQL server has gone away')
2019-01-10 20:51:28 [ERROR] assets.py[line:358] 统计机房主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:51:28 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:51:46 [ERROR] assets.py[line:350] 统计项目主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:51:46 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:51:46 [ERROR] assets.py[line:374] 统计资产类型失败:(2006, 'MySQL server has gone away')
2019-01-10 20:51:46 [ERROR] assets.py[line:358] 统计机房主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:51:46 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:53:46 [ERROR] assets.py[line:350] 统计项目主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:53:46 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:53:46 [ERROR] assets.py[line:374] 统计资产类型失败:(2006, 'MySQL server has gone away')
2019-01-10 20:53:46 [ERROR] assets.py[line:358] 统计机房主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:53:46 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:54:07 [ERROR] assets.py[line:350] 统计项目主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:54:07 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:54:07 [ERROR] assets.py[line:374] 统计资产类型失败:(2006, 'MySQL server has gone away')
2019-01-10 20:54:07 [ERROR] assets.py[line:358] 统计机房主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:54:08 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:54:35 [ERROR] assets.py[line:350] 统计项目主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:54:35 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:54:35 [ERROR] assets.py[line:374] 统计资产类型失败:(2006, 'MySQL server has gone away')
2019-01-10 20:54:35 [ERROR] assets.py[line:358] 统计机房主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:54:35 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:55:01 [ERROR] assets.py[line:350] 统计项目主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:55:01 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:55:01 [ERROR] assets.py[line:374] 统计资产类型失败:(2006, 'MySQL server has gone away')
2019-01-10 20:55:01 [ERROR] assets.py[line:358] 统计机房主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:55:01 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:55:16 [ERROR] assets.py[line:350] 统计项目主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:55:16 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:55:16 [ERROR] assets.py[line:374] 统计资产类型失败:(2006, 'MySQL server has gone away')
2019-01-10 20:55:16 [ERROR] assets.py[line:358] 统计机房主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:55:16 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:56:14 [ERROR] assets.py[line:350] 统计项目主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:56:14 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:56:14 [ERROR] assets.py[line:374] 统计资产类型失败:(2006, 'MySQL server has gone away')
2019-01-10 20:56:14 [ERROR] assets.py[line:358] 统计机房主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:56:14 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:56:43 [ERROR] assets.py[line:350] 统计项目主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:56:43 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:56:43 [ERROR] assets.py[line:374] 统计资产类型失败:(2006, 'MySQL server has gone away')
2019-01-10 20:56:43 [ERROR] assets.py[line:358] 统计机房主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:56:43 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:57:02 [ERROR] assets.py[line:350] 统计项目主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:57:02 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:57:02 [ERROR] assets.py[line:374] 统计资产类型失败:(2006, 'MySQL server has gone away')
2019-01-10 20:57:02 [ERROR] assets.py[line:358] 统计机房主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:57:02 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:57:31 [ERROR] assets.py[line:350] 统计项目主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:57:31 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:57:31 [ERROR] assets.py[line:374] 统计资产类型失败:(2006, 'MySQL server has gone away')
2019-01-10 20:57:31 [ERROR] assets.py[line:358] 统计机房主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 20:57:31 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 21:44:28 [ERROR] assets.py[line:350] 统计项目主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 21:44:28 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 21:44:28 [ERROR] assets.py[line:374] 统计资产类型失败:(2006, 'MySQL server has gone away')
2019-01-10 21:44:28 [ERROR] assets.py[line:358] 统计机房主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 21:44:28 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 22:31:00 [ERROR] assets.py[line:350] 统计项目主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 22:31:00 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 22:31:00 [ERROR] assets.py[line:374] 统计资产类型失败:(2006, 'MySQL server has gone away')
2019-01-10 22:31:00 [ERROR] assets.py[line:358] 统计机房主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 22:31:00 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 22:32:33 [ERROR] assets.py[line:350] 统计项目主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 22:32:33 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 22:32:33 [ERROR] assets.py[line:374] 统计资产类型失败:(2006, 'MySQL server has gone away')
2019-01-10 22:32:33 [ERROR] assets.py[line:358] 统计机房主机资产失败:(2006, 'MySQL server has gone away')
2019-01-10 22:32:33 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-11 21:54:45 [ERROR] assets.py[line:350] 统计项目主机资产失败:(2006, 'MySQL server has gone away')
2019-01-11 21:54:45 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-11 21:54:45 [ERROR] assets.py[line:374] 统计资产类型失败:(2006, 'MySQL server has gone away')
2019-01-11 21:54:45 [ERROR] assets.py[line:358] 统计机房主机资产失败:(2006, 'MySQL server has gone away')
2019-01-11 21:54:45 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-11 21:54:57 [ERROR] assets.py[line:350] 统计项目主机资产失败:(2006, 'MySQL server has gone away')
2019-01-11 21:54:57 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-11 21:54:57 [ERROR] assets.py[line:374] 统计资产类型失败:(2006, 'MySQL server has gone away')
2019-01-11 21:54:57 [ERROR] assets.py[line:358] 统计机房主机资产失败:(2006, 'MySQL server has gone away')
2019-01-11 21:54:57 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-11 21:55:05 [ERROR] assets.py[line:350] 统计项目主机资产失败:(2006, 'MySQL server has gone away')
2019-01-11 21:55:05 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-11 21:55:05 [ERROR] assets.py[line:374] 统计资产类型失败:(2006, 'MySQL server has gone away')
2019-01-11 21:55:05 [ERROR] assets.py[line:358] 统计机房主机资产失败:(2006, 'MySQL server has gone away')
2019-01-11 21:55:05 [ERROR] assets.py[line:366] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-12 10:23:56 [ERROR] assets.py[line:392] 统计数据库类型失败:'NoneType' object is not iterable
2019-01-12 10:39:38 [ERROR] base.py[line:181] 创建列表类型连接池失败: (2003, "Can't connect to MySQL server on '192.168.1.235' (111)")
2019-01-12 10:54:19 [ERROR] assets.py[line:409] 统计代码发布类型失败:'Tags_Assets' object has no attribute 'tags_server_assets'
2019-01-12 21:31:11 [ERROR] base.py[line:181] 创建列表类型连接池失败: (2003, "Can't connect to MySQL server on '192.168.1.235' (111)")
2019-01-13 16:25:57 [WARNING] database.py[line:187] 用户分配数据库失败: (1062, "Duplicate entry '1-1' for key 'opsmanage_database_user_db_user_a8f95aa4_uniq'")
2019-01-13 16:27:22 [WARNING] database.py[line:187] 用户分配数据库失败: (1062, "Duplicate entry '1-1' for key 'opsmanage_database_user_db_user_a8f95aa4_uniq'")
2019-01-13 16:29:14 [WARNING] database.py[line:187] 用户分配数据库失败: (1062, "Duplicate entry '1-1' for key 'opsmanage_database_user_db_user_a8f95aa4_uniq'")
2019-01-13 16:41:55 [ERROR] base.py[line:181] 创建列表类型连接池失败: (2003, "Can't connect to MySQL server on '192.168.1.235' (111)")
2019-01-13 17:09:08 [ERROR] database.py[line:190] DBUser没有get_user_database方法
2019-01-13 17:17:15 [ERROR] database.py[line:190] DBUser没有query_user_db方法
2019-01-13 17:42:05 [ERROR] database.py[line:190] DBUser没有query_user_db方法
2019-01-13 17:42:06 [ERROR] database.py[line:190] DBUser没有query_user_db方法
2019-01-13 17:42:06 [ERROR] database.py[line:190] DBUser没有query_user_db方法
2019-01-13 17:42:07 [ERROR] database.py[line:190] DBUser没有query_user_db方法
2019-01-13 17:42:07 [ERROR] database.py[line:190] DBUser没有query_user_db方法
2019-01-13 17:42:08 [ERROR] database.py[line:190] DBUser没有get_all_user_database方法
2019-01-13 17:42:08 [ERROR] database.py[line:190] DBUser没有get_user_database方法
2019-01-13 17:42:09 [ERROR] database.py[line:190] DBUser没有get_user_database方法
2019-01-13 18:10:11 [ERROR] database.py[line:182] 查询数据库失败: 'DataBase_Server_Config' object has no attribute 'assets'
2019-01-13 18:10:11 [ERROR] database.py[line:182] 查询数据库失败: 'DataBase_Server_Config' object has no attribute 'assets'
2019-01-13 18:10:11 [ERROR] database.py[line:182] 查询数据库失败: 'DataBase_Server_Config' object has no attribute 'assets'
2019-01-13 19:31:26 [ERROR] base.py[line:181] 创建列表类型连接池失败: (2003, "Can't connect to MySQL server on '192.168.1.235' (111)")
2019-01-13 21:44:18 [ERROR] base.py[line:181] 创建列表类型连接池失败: (2003, "Can't connect to MySQL server on '192.168.1.235' (111)")
2019-01-19 13:01:00 [ERROR] users.py[line:186] GroupManage没有get_users方法
2019-01-19 13:01:06 [ERROR] users.py[line:186] GroupManage没有get_users方法
2019-01-19 13:26:28 [ERROR] users.py[line:186] GroupManage没有get_users方法
2019-01-19 13:26:30 [ERROR] users.py[line:186] GroupManage没有get_users方法
2019-01-19 13:26:32 [ERROR] users.py[line:186] GroupManage没有get_users方法
2019-01-19 13:26:33 [ERROR] users.py[line:186] GroupManage没有get_users方法
2019-01-19 13:26:35 [ERROR] users.py[line:186] GroupManage没有get_users方法
2019-01-19 13:26:37 [ERROR] users.py[line:186] GroupManage没有get_users方法
2019-01-19 23:28:17 [ERROR] orders.py[line:75] ApplyManage没有__inception方法
2019-01-19 23:29:06 [ERROR] orders.py[line:75] ApplyManage没有__inception方法
2019-01-20 00:25:41 [ERROR] orders.py[line:140] SQL审核失败: (1146, "Table 'opsmanage.opsmanage_fileupload_audit_order' doesn't exist")
2019-01-20 00:36:09 [ERROR] orders.py[line:125] SQL审核失败: (1062, "Duplicate entry '测试1-1-0' for key 'opsmanage_order_system_order_subject_order_user_43930f38_uniq'")
2019-01-20 00:43:02 [ERROR] orders.py[line:125] SQL审核失败: (1062, "Duplicate entry '测试1-1-0' for key 'opsmanage_order_system_order_subject_order_user_43930f38_uniq'")
2019-01-20 12:01:25 [WARNING] backend.py[line:648] uid=alex,ou=people,dc=opsmanage,dc=com does not have a value for the attribute givenName
2019-01-20 15:56:24 [WARNING] orders.py[line:212] 获取工单信息失败: Order_System matching query does not exist.
2019-01-20 16:09:54 [WARNING] orders.py[line:212] 获取工单信息失败: Order_System matching query does not exist.
2019-01-20 16:13:00 [WARNING] orders.py[line:212] 获取工单信息失败: Order_System matching query does not exist.
2019-01-20 16:14:35 [WARNING] orders.py[line:212] 获取工单信息失败: Order_System matching query does not exist.
2019-01-20 16:14:44 [WARNING] orders.py[line:212] 获取工单信息失败: Order_System matching query does not exist.
2019-01-20 18:45:36 [WARNING] orders.py[line:227] 获取工单信息失败: Order_System matching query does not exist.
2019-01-20 22:25:31 [WARNING] server.py[line:223] Application instance <Task pending coro=<AsgiHandler.__call__() running at /usr/local/python3/lib/python3.6/site-packages/channels/http.py:202> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/python3/lib/python3.6/asyncio/futures.py:403, <TaskWakeupMethWrapper object at 0x7f366014a948>()]>> for connection <WebRequest at 0x7f3660130f28 method=POST uri=/order/handle/ clientproto=HTTP/1.1> took too long to shut down and was killed.
2019-01-20 22:59:00 [ERROR] inception.py[line:180] Mysql Error 2003: Can't connect to MySQL server on '192.168.1.233' ([Errno 111] Connection refused)
2019-01-20 23:00:04 [ERROR] inception.py[line:180] Mysql Error 2003: Can't connect to MySQL server on '192.168.1.233' ([Errno 111] Connection refused)
2019-01-20 23:00:47 [ERROR] inception.py[line:180] Mysql Error 2003: Can't connect to MySQL server on '192.168.1.233' ([Errno 111] Connection refused)
2019-01-20 23:01:15 [ERROR] inception.py[line:180] Mysql Error 2003: Can't connect to MySQL server on '192.168.1.233' ([Errno 111] Connection refused)
2019-01-20 23:01:53 [ERROR] inception.py[line:180] Mysql Error 2003: Can't connect to MySQL server on '192.168.1.233' ([Errno 111] Connection refused)
2019-01-20 23:02:29 [ERROR] inception.py[line:180] Mysql Error 2003: Can't connect to MySQL server on '192.168.1.233' ([Errno 111] Connection refused)
2019-01-20 23:02:31 [ERROR] inception.py[line:180] Mysql Error 2003: Can't connect to MySQL server on '192.168.1.233' ([Errno 111] Connection refused)
2019-01-20 23:03:22 [ERROR] inception.py[line:180] Mysql Error 2003: Can't connect to MySQL server on '192.168.1.233' ([Errno 111] Connection refused)
2019-01-21 11:00:52 [WARNING] orders.py[line:218] 获取工单信息失败: Order_System matching query does not exist.
2019-01-21 11:00:52 [WARNING] orders.py[line:192] 获取数据库信息失败: 'bool' object has no attribute 'sql_audit_order'
2019-01-21 11:28:18 [ERROR] orders.py[line:235] OrderStatus没有get_rollback_sql方法
2019-01-21 11:28:27 [WARNING] orders.py[line:209] 获取工单信息失败: Order_System matching query does not exist.
2019-01-21 11:28:27 [WARNING] orders.py[line:191] 获取数据库信息失败: 'bool' object has no attribute 'sql_audit_order'
2019-01-21 11:34:03 [ERROR] orders.py[line:318] OrderManage没有sql方法
2019-01-21 11:37:57 [ERROR] orders.py[line:318] OrderManage没有get_osc方法
2019-01-21 12:07:11 [ERROR] orders.py[line:253] OrderStatus没有exec_sql方法
2019-01-21 14:51:28 [ERROR] orders.py[line:318] OrderManage没有stop_osc方法
2019-01-21 18:38:05 [ERROR] deploy_api.py[line:143] 添加资产组，转化外部变量失败: unexpected EOF while parsing (<string>, line 0)
2019-01-21 21:17:49 [ERROR] deploy_api.py[line:149] 添加资产组，转化外部变量失败: unexpected EOF while parsing (<string>, line 0)
2019-01-21 21:17:53 [ERROR] deploy_api.py[line:149] 添加资产组，转化外部变量失败: unexpected EOF while parsing (<string>, line 0)
2019-01-21 21:18:03 [ERROR] deploy_api.py[line:149] 添加资产组，转化外部变量失败: unexpected EOF while parsing (<string>, line 0)
2019-01-21 21:46:18 [ERROR] assets.py[line:139] AssetsBase没有deploy_group方法
2019-01-21 21:46:21 [ERROR] assets.py[line:139] AssetsBase没有deploy_group方法
2019-01-21 21:46:24 [ERROR] assets.py[line:139] AssetsBase没有deploy_group方法
2019-01-21 21:46:26 [ERROR] assets.py[line:139] AssetsBase没有deploy_group方法
2019-01-21 23:59:28 [WARNING] dispos.py[line:108] 添加部署脚本失败: (1062, "Duplicate entry '测试脚本' for key 'script_name'")
2019-01-22 21:39:35 [ERROR] dispos.py[line:209] 更新剧本失败: (1406, "Data too long for column 'playbook_type' at row 1")
2019-01-22 21:40:17 [ERROR] dispos.py[line:209] 更新剧本失败: (1406, "Data too long for column 'playbook_type' at row 1")
2019-01-22 21:40:47 [ERROR] dispos.py[line:209] 更新剧本失败: (1406, "Data too long for column 'playbook_type' at row 1")
2019-01-22 21:42:43 [ERROR] dispos.py[line:209] 更新剧本失败: (1406, "Data too long for column 'playbook_type' at row 1")
2019-01-22 21:58:03 [WARNING] dispos.py[line:108] 添加部署脚本失败: (1062, "Duplicate entry '测试脚本' for key 'script_name'")
2019-01-25 22:16:32 [ERROR] base.py[line:181] 创建列表类型连接池失败: (2003, "Can't connect to MySQL server on '192.168.1.235' ([Errno 111] Connection refused)")
2019-01-25 22:54:37 [ERROR] users.py[line:42] UsersManage没有get_user_assets方法
2019-01-26 09:55:45 [WARNING] users.py[line:54] 获取用户信息失败: User matching query does not exist.
2019-01-26 10:00:18 [WARNING] users.py[line:54] 获取用户信息失败: User matching query does not exist.
2019-01-26 10:12:53 [WARNING] users.py[line:54] 获取用户信息失败: User matching query does not exist.
2019-01-26 10:13:45 [WARNING] users.py[line:54] 获取用户信息失败: User matching query does not exist.
2019-01-26 10:14:04 [WARNING] users.py[line:54] 获取用户信息失败: User matching query does not exist.
2019-01-26 10:14:38 [WARNING] users.py[line:54] 获取用户信息失败: User matching query does not exist.
2019-01-26 10:15:02 [WARNING] users.py[line:54] 获取用户信息失败: User matching query does not exist.
2019-01-26 10:15:27 [WARNING] users.py[line:54] 获取用户信息失败: User matching query does not exist.
2019-01-26 10:17:43 [WARNING] users.py[line:54] 获取用户信息失败: User matching query does not exist.
2019-01-26 10:17:56 [WARNING] users.py[line:54] 获取用户信息失败: User matching query does not exist.
2019-01-26 10:18:46 [WARNING] users.py[line:54] 获取用户信息失败: User matching query does not exist.
2019-01-26 10:19:30 [WARNING] users.py[line:54] 获取用户信息失败: User matching query does not exist.
2019-01-26 10:41:44 [WARNING] users.py[line:54] 获取用户信息失败: User matching query does not exist.
2019-01-26 10:42:24 [WARNING] users.py[line:54] 获取用户信息失败: User matching query does not exist.
2019-01-26 10:42:58 [WARNING] users.py[line:54] 获取用户信息失败: User matching query does not exist.
2019-01-26 11:40:45 [WARNING] assets.py[line:227] 查询主机项目信息失败: 'dict' object has no attribute 'project'
2019-01-26 11:40:45 [WARNING] assets.py[line:232] 查询主机应用信息失败: 'dict' object has no attribute 'business'
2019-01-26 11:40:45 [WARNING] assets.py[line:227] 查询主机项目信息失败: 'dict' object has no attribute 'project'
2019-01-26 11:40:45 [WARNING] assets.py[line:232] 查询主机应用信息失败: 'dict' object has no attribute 'business'
2019-01-26 11:40:57 [WARNING] assets.py[line:227] 查询主机项目信息失败: 'dict' object has no attribute 'project'
2019-01-26 11:40:57 [WARNING] assets.py[line:232] 查询主机应用信息失败: 'dict' object has no attribute 'business'
2019-01-26 11:40:57 [WARNING] assets.py[line:227] 查询主机项目信息失败: 'dict' object has no attribute 'project'
2019-01-26 11:40:57 [WARNING] assets.py[line:232] 查询主机应用信息失败: 'dict' object has no attribute 'business'
2019-01-26 13:10:42 [ERROR] assets.py[line:139] AssetsBase没有tags方法
2019-01-26 21:52:06 [WARNING] server.py[line:223] Application instance <Task pending coro=<AsgiHandler.__call__() running at /usr/local/python3/lib/python3.6/site-packages/channels/http.py:202> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/python3/lib/python3.6/asyncio/futures.py:403, <TaskWakeupMethWrapper object at 0x7f5fdc6dec78>()]>> for connection <WebRequest at 0x7f5fdc51ab70 method=POST uri=/assets/batch/ clientproto=HTTP/1.1> took too long to shut down and was killed.
2019-01-27 11:22:42 [ERROR] orders.py[line:398] OrderManage没有fileupload方法
2019-01-27 11:23:39 [ERROR] orders.py[line:355] OrderStatus没有fileupload方法
2019-01-27 11:25:28 [ERROR] orders.py[line:355] OrderStatus没有fileupload方法
2019-01-27 11:28:00 [ERROR] orders.py[line:355] OrderStatus没有fileupload方法
2019-01-27 11:28:14 [ERROR] orders.py[line:355] OrderStatus没有fileupload方法
2019-01-27 11:28:40 [ERROR] orders.py[line:355] OrderStatus没有fileupload方法
2019-01-27 11:30:33 [ERROR] orders.py[line:355] OrderStatus没有fileupload方法
2019-01-27 11:31:25 [ERROR] orders.py[line:355] OrderStatus没有fileupload方法
2019-01-27 11:32:16 [ERROR] orders.py[line:355] OrderStatus没有fileupload方法
2019-01-27 11:32:57 [ERROR] orders.py[line:355] OrderStatus没有fileupload方法
2019-01-27 11:35:14 [ERROR] orders.py[line:355] OrderStatus没有fileupload方法
2019-01-27 11:35:50 [ERROR] orders.py[line:355] OrderStatus没有fileupload方法
2019-01-27 15:15:00 [ERROR] orders.py[line:358] OrderStatus没有upload方法
2019-01-27 18:36:47 [ERROR] orders.py[line:358] OrderStatus没有2方法
2019-01-27 18:46:31 [WARNING] orders.py[line:271] 获取工单信息失败: invalid literal for int() with base 10: '19/'
2019-01-27 18:47:08 [WARNING] orders.py[line:271] 获取工单信息失败: invalid literal for int() with base 10: '18/'
2019-01-27 21:10:29 [ERROR] orders.py[line:119] SQL审核失败: (1062, "Duplicate entry '测试多个文件分发-1-2' for key 'opsmanage_order_system_order_subject_order_user_43930f38_uniq'")
2019-01-27 21:12:37 [ERROR] orders.py[line:119] SQL审核失败: (1062, "Duplicate entry '测试多个文件分发-1-2' for key 'opsmanage_order_system_order_subject_order_user_43930f38_uniq'")
2019-01-27 21:13:12 [ERROR] orders.py[line:119] SQL审核失败: (1062, "Duplicate entry '测试多个文件分发-1-2' for key 'opsmanage_order_system_order_subject_order_user_43930f38_uniq'")
2019-01-27 23:11:18 [ERROR] assets.py[line:129] 获取资产失败:int() argument must be a string, a bytes-like object or a number, not 'AsgiRequest'
2019-01-27 23:13:18 [WARNING] app.py[line:210] 获取项目角色管理成员失败: User matching query does not exist.
2019-01-28 19:41:29 [WARNING] app.py[line:211] 获取项目角色管理成员失败: User matching query does not exist.
2019-01-28 19:42:24 [WARNING] app.py[line:212] 获取项目角色管理成员失败: User matching query does not exist.
2019-01-28 19:54:04 [WARNING] app.py[line:220] 获取项目角色管理成员失败: User matching query does not exist.
2019-01-28 19:54:25 [WARNING] app.py[line:220] 获取项目角色管理成员失败: User matching query does not exist.
2019-01-28 20:42:43 [ERROR] orders.py[line:187] ApplyManage没有download_audit方法
2019-01-28 20:43:45 [ERROR] orders.py[line:384] OrderStatus没有filedown方法
2019-01-28 20:48:10 [ERROR] orders.py[line:384] OrderStatus没有filedown方法
2019-01-28 21:06:01 [ERROR] orders.py[line:393] OrderStatus没有filedown方法
2019-01-28 22:47:02 [ERROR] orders.py[line:706] 检查文件分发资产失败:'Struct' object has no attribute 'ip'
2019-01-29 21:18:13 [WARNING] app.py[line:219] 获取项目角色管理成员失败: User matching query does not exist.
2019-01-29 21:18:20 [WARNING] app.py[line:219] 获取项目角色管理成员失败: User matching query does not exist.
2019-01-29 23:00:30 [ERROR] assets.py[line:347] 统计项目主机资产失败:(2006, 'MySQL server has gone away')
2019-01-29 23:00:30 [ERROR] assets.py[line:363] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-29 23:00:30 [ERROR] assets.py[line:371] 统计资产类型失败:(2006, 'MySQL server has gone away')
2019-01-29 23:00:30 [ERROR] assets.py[line:355] 统计机房主机资产失败:(2006, 'MySQL server has gone away')
2019-01-29 23:00:30 [ERROR] assets.py[line:363] 统计状态主机资产失败:(2006, 'MySQL server has gone away')
2019-01-29 23:00:30 [ERROR] assets.py[line:396] 统计代码发布类型失败:(2006, 'MySQL server has gone away')
2019-01-29 23:00:30 [ERROR] assets.py[line:383] 统计数据库类型失败:(2006, 'MySQL server has gone away')
